CONTRACTOR = 'CONTRACTOR'
ARCHITECT = 'ARCHITECT'
DESIGNER = 'DESIGNER'

PROFESSIONAL_TYPE_CHOICES = (
    (CONTRACTOR, 'Contractor'),
    (ARCHITECT, 'Architect'),
    (DESIGNER, 'Designer'),
)



CONTRACTOR_TYPE_CHOICES = (

)