# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meisters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meister',
            name='lic_num',
            field=models.IntegerField(null=True),
        ),
    ]
