# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meisters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meister',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
