# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_num', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('entity_type', models.CharField(choices=[(b'FIRM', b'Firm'), (b'INDIVIDUAL', b'Individual')], max_length=64)),
                ('type', models.CharField(choices=[(b'CONTRACTOR', b'Contractor'), (b'ARCHITECT', b'Architect'), (b'DESIGNER', b'Designer')], max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('subtype', models.CharField(choices=[(b'GC', b'General Contractors'), (b'LC', b'Landscape Contractors'), (b'SPC', b'Swimming Pool Contractors'), (b'KBR', b'Kitchen & Bath Remodelor'), (b'RG', b'Roofing & Gutters'), (b'PL', b'Plumbers'), (b'FC', b'Fence Contractors'), (b'HA', b'HV & AC'), (b'DE', b'Designers')], max_length=64)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_types', related_query_name='professional_type', to='professionals.Professional')),
            ],
        ),
    ]
