# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='lic_type',
            field=models.CharField(default='N/A', max_length=256),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='professionaltype',
            name='subtype',
            field=models.CharField(choices=[(b'GC', b'General Contractors'), (b'LC', b'Landscape Contractors'), (b'SPC', b'Swimming Pool Contractors'), (b'KBR', b'Kitchen & Bath Remodelor'), (b'RG', b'Roofing & Gutters'), (b'PL', b'Plumbers'), (b'FC', b'Fence Contractors'), (b'HA', b'HV & AC'), (b'DE', b'Designers')], max_length=128),
        ),
        migrations.AlterField(
            model_name='professionaltype',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
