# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_auto_20171009_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='lic_type',
            field=models.TextField(default='NO LIC TYPE'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='postal_code',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
