# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_auto_20170925_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='lic_type',
            field=models.CharField(default='NO LIC TYPE', max_length=256),
        ),
    ]
