# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_auto_20171117_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='county',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
