# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_auto_20171211_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='type',
            field=models.CharField(choices=[(b'CONTRACTOR', 'Contractor'), (b'ARCHITECT', 'Architect'), (b'DESIGNER', 'Designer'), (b'MEISTER', 'Meister')], max_length=63),
        ),
    ]
