# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_auto_20171211_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_info', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='postal_code',
            new_name='csp',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='lic_num',
        ),
        migrations.AddField(
            model_name='professional',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='bus_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='pos_code',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional'),
        ),
    ]
