# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_auto_20171230_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='county',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='entity_type',
            field=models.CharField(blank=True, choices=[(b'Corporation', 'Corporation'), (b'Partnership', 'Partnership'), (b'Sole Ownership', 'Sole Ownership')], max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='lic_num',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='professional',
            name='lic_type',
            field=models.TextField(blank=True, default='NO LIC TYPE', null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='state',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='type',
            field=models.CharField(blank=True, choices=[(b'CONTRACTOR', 'Contractor'), (b'ARCHITECT', 'Architect'), (b'DESIGNER', 'Designer'), (b'MEISTER', 'Meister')], max_length=63, null=True),
        ),
    ]
