# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_datasourceelapso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSourceElapso',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='bus_name',
        ),
    ]
