# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_auto_20180116_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='lic_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
