# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_professional_lic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='type',
            field=models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('ARCHITECT', 'Architect'), ('DESIGNER', 'Designer'), ('MEISTER', 'Meister'), ('PROFESSIONAL', 'Professional')], max_length=10),
        ),
    ]
