# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('professionals', '0010_auto_20180117_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='professional_info',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='lic_num',
            field=models.CharField(default='0', max_length=127),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='uuid',
            field=models.CharField(default='0', max_length=36),
        ),
    ]
