# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20180216_0732'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('F', 'FAILED'), ('S', 'SUCCESS'), ('A', 'ABORTED'), ('C', 'CANCELED')], default='P', max_length=8, verbose_name='transaction status')),
                ('transaction_key', models.CharField(max_length=32, unique=True)),
                ('uuid', models.CharField(default='0', max_length=36)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', related_query_name='transaction', to='projects.Milestone')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', related_query_name='transaction', to='projects.Project', verbose_name='project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('F', 'FAILED'), ('S', 'SUCCESS'), ('A', 'ABORTED'), ('C', 'CANCELED')], max_length=8, verbose_name='transaction status')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_histories', related_query_name='transaction_history', to='transactions.Transaction')),
            ],
        ),
    ]
