# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_uuid',
            new_name='uuid',
        ),
    ]
