# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
