# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20171117_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', related_query_name='transaction', to='projects.Project', verbose_name='project'),
        ),
    ]
