# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20171117_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_uuid',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
