# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_milestone'),
        ('transactions', '0006_auto_20171130_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='milestone',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', related_query_name='transaction', to='projects.Milestone'),
            preserve_default=False,
        ),
    ]
