# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('R', 'REMODEL'), ('N', 'NEW BUILT HOUSE')], max_length=255)),
                ('project_date', models.DateField()),
                ('street_address', models.TextField()),
                ('street_address2', models.TextField()),
                ('county', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zipcode', models.CharField(max_length=10)),
                ('project_zipcode', models.CharField(max_length=20)),
                ('project_cost', models.IntegerField()),
                ('project_duration', models.IntegerField()),
                ('comments', models.TextField()),
                ('is_anonymous', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=3)),
                ('review_status', models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='A', max_length=1)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
