# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
