# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
