# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20170925_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('R', 'REJECTED')], default='A', max_length=1),
        ),
    ]
