# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hscores', related_query_name='hscore', to='contractors.Contractor')),
            ],
        ),
    ]
