# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
            ],
        ),
    ]
