# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscore',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hscore',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hscore',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
