# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_auto_20171009_2256'),
        ('hscore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hscore',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='hscore',
            name='object_id',
        ),
        migrations.AddField(
            model_name='hscore',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hscores', related_query_name='hscore', to='contractors.Contractor'),
        ),
    ]
