# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefield',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='filefield',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
