# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backgroundphoto',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
