# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=32)),
            ],
        ),
    ]
