# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerinterest',
            name='consumer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumer_interests', related_query_name='consumer_interest', to='users.ConsumerProfile'),
        ),
        migrations.AlterField(
            model_name='consumerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consumer_profiles', related_query_name='consumer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professional_profiles', related_query_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
