# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171117_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoomeId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoome_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[(b'H', 'Hold'), (b'B', 'Bad'), (b'S', 'Signed'), (b'A', 'Available')], max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hoome_id',
            field=models.CharField(default='10000000', max_length=32),
            preserve_default=False,
        ),
    ]
