# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('lic_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('lic_prefix', models.CharField(max_length=2)),
                ('lic_name', models.CharField(max_length=64)),
                ('lic_type', models.CharField(max_length=64)),
                ('lic_status', models.CharField(max_length=64)),
                ('issue_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=64)),
                ('county', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=64)),
                ('actions', models.CharField(max_length=64)),
            ],
        ),
    ]
