# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('lic_id', models.AutoField(primary_key=True, serialize=False)),
                ('lic_num', models.CharField(max_length=63)),
                ('lic_prefix', models.CharField(max_length=2)),
                ('lic_name', models.CharField(max_length=63)),
                ('lic_type', models.CharField(max_length=10)),
                ('lic_status', models.CharField(max_length=63)),
                ('lic_issue_date', models.DateField(blank=True, null=True)),
                ('lic_expire_date', models.DateField(blank=True, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=63)),
                ('county', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('country', models.CharField(max_length=63)),
                ('pos_code', models.CharField(max_length=25)),
                ('actions', models.CharField(max_length=63)),
                ('uuid', models.CharField(default='0', max_length=36)),
                ('license_board', models.CharField(blank=True, default='California Architect State License Board', max_length=255, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='architect',
            unique_together=set([('lic_num', 'lic_type', 'license_board')]),
        ),
    ]
