# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='architect',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
