# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='architect_uuid',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
