# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0002_auto_20171007_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='actions',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='architect',
            name='city',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='country',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='county',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='lic_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='lic_status',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='lic_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='architect',
            name='state',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='architect',
            name='zip',
            field=models.CharField(max_length=25),
        ),
    ]
