# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0002_architect_architect_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='uuid',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
