# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0003_auto_20171130_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='architect_uuid',
            field=models.CharField(default='0', max_length=36),
        ),
    ]
