# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0003_auto_20171009_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architect',
            old_name='address',
            new_name='street_address',
        ),
    ]
