# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0004_auto_20171202_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architect',
            old_name='architect_uuid',
            new_name='uuid',
        ),
    ]
