# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0004_auto_20171202_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='architect_uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
