# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0004_auto_20171021_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architect',
            old_name='zip',
            new_name='pos_code',
        ),
    ]
