# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0005_auto_20171030_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architect',
            old_name='expire_date',
            new_name='lic_expire_date',
        ),
        migrations.RenameField(
            model_name='architect',
            old_name='issue_date',
            new_name='lic_issue_date',
        ),
    ]
