# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0006_auto_20171102_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architect',
            name='lic_expire_date',
        ),
        migrations.AddField(
            model_name='architect',
            name='Lic_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
