# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0007_auto_20171103_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architect',
            old_name='Lic_expire_date',
            new_name='lic_expire_date',
        ),
    ]
