# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', tinymce.models.HTMLField()),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.Professional')),
            ],
        ),
    ]
