# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceElapso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_num', models.CharField(max_length=127)),
                ('lic_type', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=63)),
                ('lic_state', models.CharField(max_length=15)),
                ('lic_board', models.CharField(max_length=255)),
                ('lic_status', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('state_lic_num', models.CharField(max_length=127)),
                ('name2', models.CharField(max_length=63)),
                ('bussiness_lic_num', models.CharField(max_length=63)),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('lic_issue_date', models.DateField()),
                ('lic_expire_date', models.DateField()),
                ('bus_expire_date', models.DateField()),
                ('insur_company', models.CharField(max_length=63)),
                ('insur_policy', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
