# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('lic_id', models.AutoField(primary_key=True, serialize=False)),
                ('lic_num', models.CharField(max_length=63)),
                ('lic_type', models.CharField(max_length=10)),
                ('lic_name', models.CharField(max_length=63)),
                ('bus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_location_name', models.CharField(max_length=62)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('state_designer_num', models.CharField(blank=True, max_length=15, null=True)),
                ('contractor_lic_num', models.CharField(blank=True, max_length=15, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=63, null=True)),
                ('state', models.CharField(blank=True, max_length=63, null=True)),
                ('pos_code', models.CharField(blank=True, max_length=25, null=True)),
                ('country', models.CharField(blank=True, max_length=63, null=True)),
                ('uuid', models.CharField(default='0', max_length=36)),
                ('license_board', models.CharField(blank=True, default='NCIDQ Certification', max_length=255, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='designer',
            unique_together=set([('lic_num', 'lic_type', 'license_board')]),
        ),
    ]
