# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('lic_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('lic_type', models.CharField(max_length=62)),
                ('lic_name', models.CharField(max_length=100)),
                ('bus_name', models.CharField(blank=True, max_length=126)),
                ('office_location_name', models.CharField(max_length=62)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=62)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('state_designer_num', models.CharField(blank=True, max_length=100)),
                ('contractor_lic_num', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pos_code', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
