# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_auto_20171009_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='address',
            new_name='street_address',
        ),
    ]
