# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_designer_designer_uuid'),
        ('designers', '0002_designer_uuid'),
    ]

    operations = [
    ]
