# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0003_workercompensationhistory_insurcompany'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('E', 'Efficiency'), ('Q', 'Quality'), ('L', 'Length')], max_length=1)),
                ('count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('E', 'Efficiency'), ('Q', 'Quality'), ('L', 'Length')], max_length=1)),
                ('rating_score', models.IntegerField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
            ],
        ),
    ]
