# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
        migrations.AddField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
