# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ratings', '0002_auto_20170923_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='contractor',
        ),
        migrations.AddField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rating',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
