# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondCompany',
            fields=[
                ('SuretyCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SuretyName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=15)),
                ('PosCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BondNum', models.CharField(max_length=20)),
                ('BondAmount', models.CharField(max_length=20)),
                ('BondEffectiveDate', models.DateField()),
                ('BondCancellationDate', models.DateField()),
                ('SuretyCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.BondCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('LicNum', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('BusName', models.CharField(max_length=100)),
                ('LicStatus', models.CharField(max_length=100)),
                ('LicIssueDate', models.DateField()),
                ('LicExpireDate', models.DateField()),
                ('LicType', models.CharField(max_length=100)),
                ('Entity', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=15)),
                ('PosCode', models.IntegerField()),
                ('Phone', models.CharField(max_length=15)),
                ('LicStatusAdd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InssuranceCompany',
            fields=[
                ('InsurCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('InsurName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=15)),
                ('PosCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelatedContractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedContractor', to='contractors.Contractor')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=50)),
                ('AssociationDate', models.DateField()),
                ('LicType', models.CharField(max_length=100)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCompensationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolicyNum', models.CharField(max_length=20)),
                ('InsurEffectiveDate', models.DateField()),
                ('InsurCancellationDate', models.DateField()),
                ('InsurCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.InssuranceCompany')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
            ],
        ),
        migrations.AddField(
            model_name='licenserelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Personnel'),
        ),
        migrations.AddField(
            model_name='bondhistory',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor'),
        ),
        migrations.AlterUniqueTogether(
            name='licenserelation',
            unique_together=set([('person', 'contractor', 'RelatedContractor')]),
        ),
    ]
