# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondCompany',
            fields=[
                ('surety_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('surety_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=63, null=True)),
                ('state', models.CharField(blank=True, max_length=63, null=True)),
                ('pos_code', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BondHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surety_company', models.CharField(max_length=255)),
                ('bond_num', models.CharField(max_length=20)),
                ('bond_amount', models.CharField(max_length=20)),
                ('bond_effective_date', models.DateField(blank=True, null=True)),
                ('bond_cancellation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=255)),
                ('complain_num', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('result', models.CharField(max_length=255)),
                ('complaint_count', models.IntegerField(null=True)),
                ('code_source', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('code_detail', models.CharField(max_length=255)),
                ('doc_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintOverall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.IntegerField(null=True)),
                ('citation', models.IntegerField(null=True)),
                ('arbitration', models.IntegerField(null=True)),
                ('complaint', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('lic_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('lic_type', models.TextField()),
                ('lic_name', models.CharField(max_length=255)),
                ('lic_status', models.CharField(max_length=30)),
                ('lic_issue_date', models.DateField(blank=True, null=True)),
                ('lic_expire_date', models.DateField(blank=True, null=True)),
                ('entity', models.CharField(max_length=25)),
                ('street_address', models.CharField(max_length=255)),
                ('csp', models.CharField(blank=True, max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('pos_code', models.CharField(max_length=25)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('lic_status_add', models.TextField(blank=True, null=True)),
                ('bus_info_add', models.TextField(blank=True, null=True)),
                ('dba', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('insur_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('insur_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('pos_code', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractor', to='contractors.Contractor')),
                ('related_contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_contractor', to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('title', models.CharField(max_length=63)),
                ('association_date', models.DateField()),
                ('deassociation_date', models.DateField()),
                ('lic_type', models.CharField(max_length=63)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCompensationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insur_company', models.CharField(max_length=255)),
                ('policy_num', models.CharField(max_length=20)),
                ('insur_effective_date', models.DateField(blank=True, null=True)),
                ('insur_cancellation_date', models.DateField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor')),
                ('insur_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.InsuranceCompany')),
            ],
        ),
        migrations.AddField(
            model_name='complaintoverall',
            name='lic_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lic_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor'),
        ),
        migrations.AddField(
            model_name='bondhistory',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor'),
        ),
        migrations.AddField(
            model_name='bondhistory',
            name='surety_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.BondCompany'),
        ),
        migrations.AlterUniqueTogether(
            name='licenserelation',
            unique_together=set([('name', 'contractor', 'related_contractor')]),
        ),
    ]
