# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondCompany',
            fields=[
                ('surety_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('surety_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('pos_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BondHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surety_company', models.CharField(max_length=255)),
                ('bond_num', models.CharField(max_length=20)),
                ('bond_amount', models.CharField(max_length=20)),
                ('bond_effective_date', models.DateField()),
                ('bond_cancellation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('lic_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bus_name', models.CharField(max_length=255)),
                ('lic_status', models.CharField(blank=True, max_length=100)),
                ('lic_issue_date', models.DateField(blank=True, null=True)),
                ('lic_expire_date', models.DateField(blank=True, null=True)),
                ('lic_type', models.CharField(blank=True, max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('csp', models.CharField(blank=True, max_length=62)),
                ('state', models.CharField(max_length=62)),
                ('pos_code', models.CharField(max_length=62)),
                ('phone', models.CharField(blank=True, max_length=62)),
                ('lic_status_add', models.TextField(blank=True)),
                ('bus_info_add', models.TextField(blank=True)),
                ('dba', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='InssuranceCompany',
            fields=[
                ('insur_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('insur_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('pos_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='contractors.Contractor')),
                ('related_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_contractor', to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=50)),
                ('association_date', models.DateField()),
                ('deassociation_date', models.DateField()),
                ('lic_type', models.CharField(max_length=100)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCompensationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insur_company', models.CharField(max_length=255)),
                ('policy_num', models.CharField(max_length=20)),
                ('insur_effective_date', models.DateField()),
                ('insur_cancellation_date', models.DateField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor')),
                ('insur_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contractors.InssuranceCompany')),
            ],
        ),
        migrations.AddField(
            model_name='bondhistory',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Contractor'),
        ),
        migrations.AddField(
            model_name='bondhistory',
            name='surety_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.BondCompany'),
        ),
        migrations.AlterUniqueTogether(
            name='licenserelation',
            unique_together=set([('name', 'contractor', 'related_contractor')]),
        ),
    ]
