# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='bus_info_add',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='csp',
            field=models.CharField(blank=True, max_length=62),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='dba',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_expire_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_issue_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_status_add',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=62),
        ),
    ]
