# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='lic_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_type',
            field=models.TextField(),
        ),
    ]
