# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondhistory',
            name='SuretyCompany',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
