# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_auto_20171007_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='bus_info_add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='dba',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_status_add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
    ]
