# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_contractor_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='lic_num',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='complaintoverall',
            old_name='lic_num',
            new_name='contractor',
        ),
    ]
