# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_auto_20171210_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='license_board',
            field=models.CharField(blank=True, default='California State License Board', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_num',
            field=models.CharField(max_length=63, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together=set([('lic_num', 'lic_type', 'license_board')]),
        ),
    ]
