# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_auto_20171008_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondhistory',
            name='bond_cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondhistory',
            name='bond_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workercompensationhistory',
            name='insur_cancellation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workercompensationhistory',
            name='insur_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
