# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_auto_20171229_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='entity',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='lic_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='pos_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='state',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
