# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_auto_20171009_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserelation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.Personnel'),
        ),
    ]
