# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_auto_20171230_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='csp',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
