# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_auto_20171009_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserelation',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
