# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_auto_20171009_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='lic_status',
            field=models.CharField(max_length=30),
        ),
    ]
