# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_auto_20171009_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=255)),
                ('complain_num', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('result', models.CharField(max_length=255)),
                ('complaint_count', models.IntegerField(null=True)),
                ('code_source', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('code_detail', models.CharField(max_length=255)),
                ('doc_link', models.CharField(max_length=255)),
                ('lic_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Overall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.IntegerField(null=True)),
                ('citation', models.IntegerField(null=True)),
                ('arbitration', models.IntegerField(null=True)),
                ('complaint', models.IntegerField(null=True)),
                ('lic_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contractors.Contractor')),
            ],
        ),
    ]
