# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_complaint_complaint_overall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='bus_name',
            new_name='lic_name',
        ),
    ]
