# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0011_overview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaint_Overall',
            new_name='ComplaintOverall',
        ),
        migrations.RenameModel(
            old_name='InssuranceCompany',
            new_name='InsuranceCompany',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Overview',
        ),
    ]
