# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('uploadFile', models.FileField(upload_to='disk/upload')),
            ],
        ),
    ]
