# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disk/upload/projectphotos/%Y/%m/%d')),
            ],
        ),
    ]
