# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'W', 'Waiting'), (b'PTH', 'Payed to Hoome'), (b'PTP', 'Payed to Professional'), (b'D', 'Done'), (b'M', 'Payment Request')], default=b'W', max_length=63)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone_uuid', models.CharField(default='0', max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('bus_name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('project_type', models.CharField(blank=True, choices=[(b'', b'N/A'), (b'R', 'REMODEL'), (b'N', 'NEW BUILT HOUSE')], default='', max_length=5)),
                ('street_address', models.TextField()),
                ('street_address2', models.TextField()),
                ('county', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('zipcode', models.CharField(max_length=10)),
                ('project_cost', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_description', models.TextField()),
                ('project_status', models.CharField(default=b'W', max_length=1)),
                ('project_action', models.TextField(blank=True, null=True)),
                ('project_uuid', models.CharField(default='0', max_length=36)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(max_length=100)),
                ('project_attachment', models.FileField(upload_to='project_attachment/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_photo', models.ImageField(upload_to='projects/photos/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('project_id', 'content_type', 'object_id', 'user')]),
        ),
    ]
