# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171202_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='milestone_uuid',
            new_name='uuid',
        ),
    ]
