# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171105_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_uuid',
            field=models.CharField(choices=[('P', 'PENDING'), ('A', 'ACCEPTED'), ('O', 'ONGOING'), ('R', 'REJECTED'), ('D', 'DONE')], default='0', max_length=32),
        ),
    ]
