# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171022_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField(default='USA', max_length=255),
            preserve_default=False,
        ),
    ]
