# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
    ]
