# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(default=b'Waiting', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[(b'', b'N/A'), (b'R', 'REMODEL'), (b'N', 'NEW BUILT HOUSE')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_uuid',
            field=models.CharField(default='0', max_length=36),
        ),
    ]
