# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171205_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[(b'W', 'Waiting'), (b'PTH', 'Paid to Hoome'), (b'PTP', 'Paid to Professional'), (b'D', 'Done'), (b'M', 'Payment Request')], default=b'W', max_length=63),
        ),
    ]
