# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20171207_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[(b'R', 'REMODEL'), (b'N', 'NEW BUILT HOUSE')], default=b'R', max_length=5),
        ),
    ]
