# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[(b'W', 'Waiting'), (b'H', 'Payed to Hoome'), (b'C', 'Payed to Contractor'), (b'D', 'Done')], default=b'W', max_length=63),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(default=b'W', max_length=1),
        ),
    ]
