# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171023_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bus_name',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
